### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Vicki2468** [Tabrisrp/rich-contact-widget#2]
Hi- Can I use the rich snipets to display on other pages besides just the Home page?

I'm hoping so, I like what this does !

Thank you!

**Comment by edpalermo13** [comment]
I no longer see filter to show or hide the form on specific pages.  Any help is greatly appreciated.

**Comment by Tabrisrp** [comment]
There never was a filter to show or hide the widget on specific pages. If you need this feature, you can use the widget logic plugin : https://wordpress.org/plugins/widget-logic/

**Comment by edpalermo13** [comment]
Thank you

Very truly yours,

Edward Palermo
Palermo, Palermo & Tuohy, P.C.
1300 Veterans Highway
Hauppauge, New York 11788
p-631-265-1051
f-631-265-9157
c-631-903-3733

Ptbinjurylaw.com
Edpalermo.com

NOTICE:  This e-mail message and all attachments transmitted with it 
may contain legally privileged and confidential information intended 
solely for the use of the addressee.  If the reader of this message is not 
the intended recipient, you are hereby notified that any reading, 
dissemination, distribution, copying, or other use of this message or its 
attachments is strictly prohibited.  If you have received this message in 
error, please notify the sender immediately by telephone 
(631-265-1051) or by electronic mail (edpalermo@palermo-tuohy.com), and 
delete this message and all copies and backups thereof.
